# Generated by Django 3.0.5 on 2020-04-08 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.CharField(max_length=260)),
                ('a', models.CharField(max_length=260)),
                ('tag', models.CharField(max_length=80)),
            ],
        ),
    ]
